<div class="footer_navigation_wrapper accordion" id="accordion"
     data-mage-init='{"accordion_custom": {"breakpoint":"768", "headerClass": "accordion_links_header"}}'>
    <div data-role="collapsible" class="footer_navigation_block">
        <div class="accordion_links_header accordion_closed" data-role="trigger"><?= __('About Us') ?></div>
        <ul class="footer_navigation_list" data-role="content">
            <li class="footer_navigation_item">
                <a href="#" class="footer_navigation_link"><?= __('Company') ?></a>
            </li>
            <li class="footer_navigation_item">
                <a href="#" class="footer_navigation_link"><?= __('Career') ?></a>
            </li>
            <li class="footer_navigation_item">
                <a href="#" class="footer_navigation_link"><?= __('Contact Us') ?></a>
            </li>
            <li class="footer_navigation_item">
                <a href="#" class="footer_navigation_link"><?= __('Help') ?></a>
            </li>
        </ul>
    </div>
    <div data-role="collapsible" class="footer_navigation_block">
        <div class="accordion_links_header accordion_closed" data-role="trigger"><?= __('Fasteners') ?></div>
        <ul class="footer_navigation_list" data-role="content">
            <li class="footer_navigation_item">
                <a href="#" class="footer_navigation_link"><?= __('Nails') ?></a>
            </li>
            <li class="footer_navigation_item">
                <a href="#" class="footer_navigation_link"><?= __('Staples') ?></a>
            </li>
            <li class="footer_navigation_item">
                <a href="#" class="footer_navigation_link"><?= __('Screws') ?></a>
            </li>
            <li class="footer_navigation_item">
                <a href="#" class="footer_navigation_link"><?= __('Anchors') ?></a>
            </li>
            <li class="footer_navigation_item">
                <a href="#" class="footer_navigation_link"><?= __('Bolts Nuts & Washers') ?></a>
            </li>
        </ul>
    </div>
    <div data-role="collapsible" class="footer_navigation_block">
        <div class="accordion_links_header accordion_closed" data-role="trigger"><?= __('Nails') ?></div>
        <ul class="footer_navigation_list" data-role="content">
            <li class="footer_navigation_item">
                <a href="#" class="footer_navigation_link"><?= __('Nailers') ?></a>
            </li>
            <li class="footer_navigation_item">
                <a href="#" class="footer_navigation_link"><?= __('Staplers') ?></a>
            </li>
            <li class="footer_navigation_item">
                <a href="#" class="footer_navigation_link"><?= __('Compressors & Generators') ?></a>
            </li>
            <li class="footer_navigation_item">
                <a href="#" class="footer_navigation_link"><?= __('Power Tools') ?></a>
            </li>
            <li class="footer_navigation_item">
                <a href="#" class="footer_navigation_link"><?= __('Screw Driving Systems') ?></a>
            </li>
            <li class="footer_navigation_item">
                <a href="#" class="footer_navigation_link"><?= __('Hand Tools') ?></a>
            </li>
        </ul>
    </div>
    <div data-role="collapsible" class="footer_navigation_block">
        <div class="accordion_links_header accordion_closed" data-role="trigger"><?= __('Construction Products') ?></div>
        <ul class="footer_navigation_list" data-role="content">
            <li class="footer_navigation_item">
                <a href="#" class="footer_navigation_link"><?= __('Framing Hardware') ?></a>
            </li>
            <li class="footer_navigation_item">
                <a href="#" class="footer_navigation_link"><?= __('Surface Protection') ?></a>
            </li>
            <li class="footer_navigation_item">
                <a href="#" class="footer_navigation_link"><?= __('Weather Barriers') ?></a>
            </li>
            <li class="footer_navigation_item">
                <a href="#" class="footer_navigation_link"><?= __('Adhesives & Sealants') ?></a>
            </li>
            <li class="footer_navigation_item">
                <a href="#" class="footer_navigation_link"><?= __('Building Products') ?></a>
            </li>
            <li class="footer_navigation_item">
                <a href="#" class="footer_navigation_link"><?= __('Ladders Platforms & Scaffolding') ?></a>
            </li>
        </ul>
    </div>
    <div data-role="collapsible" class="footer_navigation_block">
        <div class="accordion_links_header accordion_closed" data-role="trigger"><?= __('Packing') ?></div>
        <ul class="footer_navigation_list" data-role="content">
            <li class="footer_navigation_item">
                <a href="#" class="footer_navigation_link"><?= __('Film') ?></a>
            </li>
            <li class="footer_navigation_item">
                <a href="#" class="footer_navigation_link"><?= __('Poly Strapping') ?></a>
            </li>
            <li class="footer_navigation_item">
                <a href="#" class="footer_navigation_link"><?= __('Corner Edge & Dunnage Protection') ?></a>
            </li>
            <li class="footer_navigation_item">
                <a href="#" class="footer_navigation_link"><?= __('Protection') ?></a>
            </li>
            <li class="footer_navigation_item">
                <a href="#" class="footer_navigation_link"><?= __('Boxes Pads & Sheets') ?></a>
            </li>
            <li class="footer_navigation_item">
                <a href="#" class="footer_navigation_link"><?= __('Interior Packaging Supplies') ?></a>
            </li>
        </ul>
    </div>
</div>