<nav class="header_nav">
    <ul class="header_nav_list">
        <li class="header_nav_item">
            <a href="#" class="header_nav_link"><?= __('Store Locator')?></a>
        </li>
        <li class="header_nav_item">
            <a href="#" class="header_nav_link"><?= __('Quick Order')?></a>
        </li>
        <li class="header_nav_item">
            <a href="#" class="header_nav_link"><?= __('Specials and Offers')?></a>
        </li>
        <li class="header_nav_item">
            <a href="#" class="header_nav_link"><?= __('Clearance')?></a>
        </li>
        <li class="header_nav_item">
            <a href="#" class="header_nav_link"><?= __('Tool Repair')?></a>
        </li>
        <li class="header_nav_item">
            <a href="#" class="header_nav_link"><?= __('Resources')?></a>
        </li>
        <li class="header_nav_item">
            <a href="#" class="header_nav_link"><?= __('Contact Us')?></a>
        </li>
    </ul>
</nav>